### ISSUE TITLE
Visualization Demo

### ISSUE THREAD

**Issue by zjl603** [TACJu/MaXTron#1]
Dear authors,

I want to use MaXTron_Video-kMaX in a high level task, 
and if there is an inference demo that produce panoptic video masks like the pictures in the README?
Could you provide the usage details please?

Thank you for your great work!

**Comment by TACJu** [comment]
Hi,

Thanks for your interest in our work! We have updated the code and instructions for producing visualization demos. Please see [GETTING_STARTED.md](https://github.com/TACJu/MaXTron/blob/main/MaXTron_Video-kMaX/GETTING_STARTED.md#inference-demo-with-pre-trained-models).

Best
