### ISSUE TITLE
Pretrained weight of MaXTron offline(ConvNeXtV2-L)

### ISSUE THREAD

**Issue by Rey-nard** [TACJu/MaXTron#2]
Dear authors,

Thank you for your great work. It seems that the download link for the pretrained weight of MaXTron offline(ConvNeXtV2-L)  is mixed up with the one of MaXTron near-online(R50). Is it possible for you to update the download link?

**Comment by Rey-nard** [comment]
Besides, when I tried to leverage the pretrained weight of  MaXTron near-online(ConvNeXtV2-L), I found that some model parameters  couldn't be found in the checkpoint.

**Comment by TACJu** [comment]
Hi Rey-nard,

Thank you for your interest in our work and sorry for the delayed response. We are currently addressing some issues with our ConvNeXtV2-L checkpoints. Once we have resolved these and verified everything, we will update the link. We apologize for any inconvenience this may cause.

**Comment by Rey-nard** [comment]
Dear author,

Thank you for letting me know about the ongoing work on the ConvNeXtV2-L checkpoints. I appreciate your efforts in resolving the issues and look forward to the updated link. Thank you for your dedication and hard work.

**Comment by TACJu** [comment]
Hi Rey-nard,

Sorry for the late response. We have reproduced the ConvNeXtV2-L model results, but there is a 0.1 performance gap compared to the results reported in the paper. We apologize for any inconvenience this may cause.
